spring.profiles.active=dev

# Ép Swagger quét ?úng package ch?a Controller
springdoc.packages-to-scan=com.example.demo.controller
# Hi?n th? ???ng d?n Swagger UI là /swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
# Không cho phép l?i tu?n hoàn làm s?p tài li?u
springdoc.model-and-view-allowed=true
#hoan thanh csdl